### PR TITLE
Support prepared select queries

### PR DESCRIPTION
**Pull request by timotaularson**

### CODE REVIEW

**Comment by MegaByte** [comment]
Was this closed by accident? The reference seems unrelated and the branch hasn't been merged.

**Comment by quinnj** [comment]
Yes, it looks like another commit accidently referenced this PR and it got closed.

**Comment by akdor1154** [comment]
ping on this... any chance of getting it in?

**Comment by quinnj** [comment]
Sorry I never got this properly reviewed/merged; it's been implemented as part of the package rewrite in https://github.com/JuliaDatabases/ODBC.jl/pull/263

**Pull request closed without merging**
