### PR TITLE
ODBC info messages changed from warn to info

### PR DESCRIPTION
**Pull request by ExpandingMan**
This was routinely emitting rather benign-looking messages for me, so I changed it to `@info`.

### CODE REVIEW

**Comment by quinnj** [comment]
@giordano, could you help me figure out the .travis.yml tweak to ensure travis runs on PRs like this? I think the changes we made were too aggressive and it's not running here?

**Comment by giordano** [comment]
I think it's GitHub that isn't showing it: https://travis-ci.org/github/JuliaDatabases/ODBC.jl/builds/693483962

**Comment by quinnj** [comment]
Ah, indeed.

**Comment by giordano** [comment]
For the record, when I don't see a Travis job showing up in GitHub, I go to the [list of requests](https://travis-ci.org/github/JuliaDatabases/ODBC.jl/requests) to see why it didn't start :wink:

**Pull request merged**
